name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Generate BuildNumber
      id: version
      run: echo "::set-output name=version::$(date +%Y.%m).${GITHUB_RUN_NUMBER}"
    - name: Create Package
      run: dotnet pack ./Octonauts.Cli/Octonauts.Cli.csproj --output ./nuget_packages --configuration Release /p:BuildNumber=${{steps.version.outputs.version}} 
    - name: publish to NuGet
      run: dotnet nuget push --api-key ${{secrets.NUGETAPIKEY}} ./nuget_packages/*.nupkg -s https://api.nuget.org/v3/index.json
    - name: Clean Workspace
      uses: AutoModality/action-clean@v1.1.0
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Create Publish-able Binaries for Win10-x86 for choco
      run: dotnet publish ./Octonauts.Cli/Octonauts.Cli.csproj --output ./Octonauts.Cli/publish --configuration Release -r win10-x86 /p:BuildNumber=${{steps.version.outputs.version}} 
    - name: Prepare nuspec for choco
      run: pwsh ./PrepareChocoPack.ps1
    - name: Prepare nuspec for choco
      run: dotnet pack ./Octonauts.Cli/Octonauts.Cli.csproj --no-build --no-restore -p:NuspecFile=Octonauts.Cli.nuspec --configuration Release --output ./nuget_packages
    - name: Push Choco package
      if: true
      uses: crazy-max/ghaction-chocolatey@v1.3.1
      with:
        args: push ./nuget_packages/Octonauts.Cli.${{steps.version.outputs.version}}.nupkg --source https://push.chocolatey.org/ --apikey ${{secrets.CHOCO_API_KEY}}